{"name": "Test login page to verify screenshot on failure", "status": "failed", "statusDetails": {"message": "AssertionError: This assertion is designed to fail to test screenshot capture.\nassert 'An Incorrect Title' == 'Swag Labs'\n  - Swag Labs\n  + An Incorrect Title", "trace": "self = <tests.test_login.TestLogin object at 0x000002115B5F3820>\n\n    @allure.title(\"Test login page to verify screenshot on failure\")\n    @allure.severity(allure.severity_level.MINOR)\n    @pytest.mark.framework_check  # We can mark this as a framework check\n    def test_login_failure_for_screenshot(self):\n        \"\"\"\n        This test purposefully fails after a successful login to verify\n        that the screenshot-on-failure mechanism is working correctly.\n        \"\"\"\n        login_page = LoginPage(self.driver)\n        env = Environment()\n        base_url = env.get_base_url()\n    \n        with allure.step(\"Navigate and perform a successful login\"):\n            login_page.navigate_to(base_url)\n            username = env.get_username()\n            password = env.get_password()\n            login_page.login(username, password)\n            assert login_page.is_login_successful(), \"Login step failed before the intended assertion.\"\n    \n        with allure.step(\"Intentionally fail the test with a bad assertion\"):\n            self.logger.info(\"Now asserting for an incorrect title to trigger a failure.\")\n    \n            expected_title = \"An Incorrect Title\"  # This is wrong on purpose\n            actual_title = login_page.get_title()\n    \n>           assert expected_title == actual_title, \"This assertion is designed to fail to test screenshot capture.\"\nE           AssertionError: This assertion is designed to fail to test screenshot capture.\nE           assert 'An Incorrect Title' == 'Swag Labs'\nE             - Swag Labs\nE             + An Incorrect Title\n\ntest_login.py:100: AssertionError"}, "description": "\n        This test purposefully fails after a successful login to verify\n        that the screenshot-on-failure mechanism is working correctly.\n        ", "steps": [{"name": "Navigate and perform a successful login", "status": "passed", "steps": [{"name": "Navigating to URL: 'https://www.saucedemo.com/'", "status": "passed", "parameters": [{"name": "url", "value": "'https://www.saucedemo.com/'"}], "start": 1750355338562, "stop": 1750355338687}, {"name": "Entering text ''standard_user'' into Element: ('id', 'user-name')", "status": "passed", "parameters": [{"name": "locator", "value": "('id', 'user-name')"}, {"name": "text", "value": "'standard_user'"}, {"name": "clear_first", "value": "True"}], "start": 1750355338687, "stop": 1750355338763}, {"name": "Entering text ''secret_sauce'' into Element: ('id', 'password')", "status": "passed", "parameters": [{"name": "locator", "value": "('id', 'password')"}, {"name": "text", "value": "'secret_sauce'"}, {"name": "clear_first", "value": "True"}], "start": 1750355338763, "stop": 1750355338842}, {"name": "Clicking Element: ('id', 'login-button')", "status": "passed", "parameters": [{"name": "locator", "value": "('id', 'login-button')"}], "start": 1750355338842, "stop": 1750355338917}, {"name": "Checking if Element is visible: ('class name', 'app_logo')", "status": "passed", "parameters": [{"name": "locator", "value": "('class name', 'app_logo')"}, {"name": "timeout", "value": "5"}], "start": 1750355338917, "stop": 1750355338934}], "start": 1750355338561, "stop": 1750355338934}, {"name": "Intentionally fail the test with a bad assertion", "status": "failed", "statusDetails": {"message": "AssertionError: This assertion is designed to fail to test screenshot capture.\nassert 'An Incorrect Title' == 'Swag Labs'\n  - Swag Labs\n  + An Incorrect Title\n", "trace": "  File \"F:\\TY_New\\PythonRMG\\HarshaFW_Python\\tests\\test_login.py\", line 100, in test_login_failure_for_screenshot\n    assert expected_title == actual_title, \"This assertion is designed to fail to test screenshot capture.\"\n"}, "steps": [{"name": "Getting page title", "status": "passed", "start": 1750355338934, "stop": 1750355338937}], "start": 1750355338934, "stop": 1750355338938}], "attachments": [{"name": "log", "source": "7c309387-cc8f-4100-af6f-fed384c301b9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "b77f9131-5509-4882-8c5d-97d866aa9772-attachment.txt", "type": "text/plain"}], "start": 1750355338559, "stop": 1750355338939, "uuid": "6f916b38-b442-40f4-b60c-0c819586d2b4", "historyId": "432039000a4f7db3ab8a0b1620edf918", "testCaseId": "432039000a4f7db3ab8a0b1620edf918", "fullName": "tests.test_login.TestLogin#test_login_failure_for_screenshot", "labels": [{"name": "story", "value": "User Login"}, {"name": "severity", "value": "minor"}, {"name": "feature", "value": "Authentication"}, {"name": "tag", "value": "framework_check"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "TYSS-Harsha"}, {"name": "thread", "value": "24252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}